# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'Swift_meipai' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire'

end

target :"API" do
    
    pod 'NSString+Ruby'
    pod 'JSONModel'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'EGOCache'
    pod 'MBProgressHUD'
    
end
